#
# options: https://github.com/kubernetes/contrib/blob/fffce5f4f933e581850b9ca67aef8b05d49650ac/ingress/controllers/nginx/examples/custom-configuration/README.md
#
apiVersion: v1
data:
  # https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#http-strict-transport-security
  hsts: "false"
  hsts-include-subdomains: "false"
  force-hsts: "false"
  body-size: "2000m"
  server-name-hash-bucket-size: "100"
  # https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#nginx-status-page
  enable-vts-status: "true"
  # Timeouts for stuff like websockets
  proxy-read-timeout: "3600"
  proxy-send-timeout: "3600"
kind: ConfigMap
metadata:
  name: nginx-load-balancer-conf
